spring:
    data:
        mongodb:
            username: cua
            password: cua
            port: 27017
            database: chat_app
            authentication-database: admin
server:
    port: 8088